### ISSUE TITLE
bug (?) mineur fonctionnalité de recherche (élément dupliqué)

### ISSUE THREAD

**Issue by LoganTann** [Creascio/bibliotheque-v2#6]
L'article *environnement de travail* apparaît trois fois dans la barre de recherche
![image](https://user-images.githubusercontent.com/28659185/122656251-07515f80-d159-11eb-808e-f2a2d8dfc7bb.png)

**Comment by Shiropetite** [comment]
@LoganTann Yes c'est en soit pas un bug mais un problème de nommage. Intro a la prog, intro à la poo et intro à la prog web ont ce chapitre en commun. On va fixer ça rapidement ! Merci du retour github en tout cas c'est super !
