### ISSUE TITLE
suggestion de design (chapitre)

### ISSUE THREAD

**Issue by LoganTann** [Creascio/bibliotheque-v2#7]
L'utilisateur passera vraisemblablement beaucoup de temps en lecture de chapitres, cette page doit donc être prioritaire au niveau de l'ergonomie

![image](https://user-images.githubusercontent.com/28659185/122656346-e9d0c580-d159-11eb-9086-ea53d7e76e08.png)

Le texte du cours prend toute la largeur de l'écran. Sur un écran HD, cela n'est pas très confortable à lire.  
Étonnamment, cette constante utilisée par bookstack fonctionne plutôt bien : ` max-width:840px; width:100%;`

Fonctionnalités possibles à envisager : 
* bouton *article précédent* et *suivant*, vu comment sont organisés les cours, ce sera plus confortable et aussi maintenable. Si aucun suivant/précédent, va en `../` pour la liste des articles
* *toc* et *listes des chapitres* minimaliste sur le côté

ref design : 
![image](https://user-images.githubusercontent.com/28659185/122656498-6dd77d00-d15b-11eb-84c0-5a10c07f4f15.png)

**Comment by Shiropetite** [comment]
@LoganTann Totalement. Dans le futur on feras la liste des chapitres sur le cotés mais la c'est pas pour tout de suite. Par contre, je vais rapidement changer la taille pour centré le texte et que ce soit plus lisible. Merci du retour ! 👍
